
name: Run Python Tests and Save Output UV

on: push
  #[push, pull_request]


jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v7

      - name: Enable caching
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      #- name: Install the project
      #  run: uv sync --locked --all-extras --dev

      #- name: Run tests
      #  # For example, using `pytest`
      #  if: always()
      #  # Moving to a temporary directory forces Python to import the 
      #  # globally installed package instead of the local source files.
      #  run: |
      #      mkdir test_env
      #      cd test_env
      #     uv run pytest -s -v ../tests > ../test_report.txt 2>&1
      #      cd ..

      - name: Build
        run: uv build
      # Check that basic features work and we didn't miss to include crucial files
      - name: Test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/test_simple.py >> test_report.txt 2>&1
      - name: Test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/test_simple.py >> test_report.txt 2>&1  

      # Upload the file to GitHub so you can download it
      - name: Upload test results file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-test-output
          path: test_report.txt        